Vagrant.configure("2") do |config|
  config.vm.box = "cisco/iosv"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  config.vm.boot_timeout = 180
  config.vm.guest = :freebsd

  config.vm.provider :libvirt do |domain|
    domain.nic_adapter_count = 8
    domain.memory = 512
    domain.cpus = 1
    domain.driver = "kvm"
    domain.nic_model_type = "e1000"
  end

  config.vm.define "c1" do |c1|
    c1.vm.network :private_network, :libvirt__network_name => "DMVPN-hub", :ip => "10.255.0.2",
                   :libvirt__forward_mode => "veryisolated", :libvirt__dhcp_enabled => false, :auto_config => false
    c1.vm.network :private_network, :ip => "10.0.7.17", :libvirt__network_name => "DMVPN-Internet",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    c1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-01"
    end
  end

  config.vm.define "c2" do |c2|
    c2.vm.network :private_network, :libvirt__network_name => "DMVPN-hub", :ip => "10.255.0.3",
                   :libvirt__forward_mode => "veryisolated", :libvirt__dhcp_enabled => false, :auto_config => false
    c2.vm.network :private_network, :ip => "10.0.7.13", :libvirt__network_name => "DMVPN-Internet",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    c2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-02"
    end
  end

  config.vm.define "r1a" do |r1a|
    r1a.vm.network :private_network, :libvirt__network_name => "DMVPN-site-1", :ip => "10.255.1.2",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    r1a.vm.network :private_network, :ip => "10.0.7.22", :libvirt__network_name => "DMVPN-Internet",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    r1a.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-03"
    end
  end

  config.vm.define "r1b" do |r1b|
    r1b.vm.network :private_network, :libvirt__network_name => "DMVPN-site-1", :ip => "10.255.1.3",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    r1b.vm.network :private_network, :ip => "10.0.7.26", :libvirt__network_name => "DMVPN-Internet",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    r1b.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-04"
    end
  end

  config.vm.define "r2" do |r2|
    r2.vm.network :private_network, :libvirt__network_name => "DMVPN-site-2", :ip => "10.255.2.2",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    r2.vm.network :private_network, :ip => "10.0.7.9", :libvirt__network_name => "DMVPN-Internet",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    r2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-05"
    end
  end

  config.vm.define "r3" do |r3|
    r3.vm.network :private_network, :libvirt__network_name => "DMVPN-site-3", :ip => "10.255.3.2",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    r3.vm.network :private_network, :ip => "10.0.7.5", :libvirt__network_name => "DMVPN-Internet",
                   :libvirt__forward_mode => "none", :libvirt__dhcp_enabled => false, :auto_config => false
    r3.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-06"
    end
  end

end
