---
- name:  Collect IOS facts from devices. Save them to YAML files
  hosts: all
  vars:
  - results: results
  tasks:
  - file: path={{results}} state=directory
    run_once: true
  - ios_facts:
    register: result
  - copy: content="{{result.ansible_facts|to_nice_yaml(indent=4)}}" dest={{results}}/{{inventory_hostname}}.yml