Vagrant.configure("2") do |config|
  config.vm.box = "cisco/iosv"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  config.vm.boot_timeout = 180
  config.vm.guest = :freebsd

  config.vm.provider :libvirt do |domain|
    domain.nic_adapter_count = 8
    domain.memory = 512
    domain.cpus = 1
    domain.driver = "kvm"
    domain.nic_model_type = "e1000"
  end

  config.vm.define "pe1" do |pe1|
    pe1.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.1",:libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.1.3",:libvirt__tunnel_port => "10001",
                  auto_config: false
    pe1.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.1",:libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.4",:libvirt__tunnel_port => "10002",
                  auto_config: false
    pe1.vm.network :private_network, :libvirt__network_name => "6-router-site-1", :ip => "10.255.10.2",
                   :libvirt__forward_mode => "veryisolated", :libvirt__dhcp_enabled => false, :auto_config => false
    pe1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-01"
    end
  end

  config.vm.define "pe2" do |pe2|
    pe2.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.2",:libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.1.5",:libvirt__tunnel_port => "10003",
                  auto_config: false
    pe2.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.2",:libvirt__tunnel_local_port => "10004",
                  :libvirt__tunnel_ip => "127.1.1.6",:libvirt__tunnel_port => "10004",
                  auto_config: false
    pe2.vm.network :private_network, :libvirt__network_name => "6-router-site-2", :ip => "10.255.11.2",
                   :libvirt__forward_mode => "veryisolated", :libvirt__dhcp_enabled => false, :auto_config => false
    pe2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-02"
    end
  end

  config.vm.define "e1" do |e1|
    e1.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.3",:libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.1.1",:libvirt__tunnel_port => "10001",
                  auto_config: false
    e1.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.3",:libvirt__tunnel_local_port => "10005",
                  :libvirt__tunnel_ip => "127.1.1.4",:libvirt__tunnel_port => "10005",
                  auto_config: false
    e1.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.3",:libvirt__tunnel_local_port => "10006",
                  :libvirt__tunnel_ip => "127.1.1.5",:libvirt__tunnel_port => "10006",
                  auto_config: false
    e1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-03"
    end
  end

  config.vm.define "e2" do |e2|
    e2.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.4",:libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.1",:libvirt__tunnel_port => "10002",
                  auto_config: false
    e2.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.4",:libvirt__tunnel_local_port => "10005",
                  :libvirt__tunnel_ip => "127.1.1.3",:libvirt__tunnel_port => "10005",
                  auto_config: false
    e2.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.4",:libvirt__tunnel_local_port => "10007",
                  :libvirt__tunnel_ip => "127.1.1.6",:libvirt__tunnel_port => "10007",
                  auto_config: false
    e2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-04"
    end
  end

  config.vm.define "e3" do |e3|
    e3.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.5",:libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.1.2",:libvirt__tunnel_port => "10003",
                  auto_config: false
    e3.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.5",:libvirt__tunnel_local_port => "10008",
                  :libvirt__tunnel_ip => "127.1.1.6",:libvirt__tunnel_port => "10008",
                  auto_config: false
    e3.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.5",:libvirt__tunnel_local_port => "10006",
                  :libvirt__tunnel_ip => "127.1.1.3",:libvirt__tunnel_port => "10006",
                  auto_config: false
    e3.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-05"
    end
  end

  config.vm.define "e4" do |e4|
    e4.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.6",:libvirt__tunnel_local_port => "10004",
                  :libvirt__tunnel_ip => "127.1.1.2",:libvirt__tunnel_port => "10004",
                  auto_config: false
    e4.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.6",:libvirt__tunnel_local_port => "10008",
                  :libvirt__tunnel_ip => "127.1.1.5",:libvirt__tunnel_port => "10008",
                  auto_config: false
    e4.vm.network :private_network,:libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.6",:libvirt__tunnel_local_port => "10007",
                  :libvirt__tunnel_ip => "127.1.1.4",:libvirt__tunnel_port => "10007",
                  auto_config: false
    e4.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-06"
    end
  end

end
